version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pet-project-app
    volumes:
      - ./pet-project:/pet-project
    environment:
      - APP_CONFIG__DB__URL=mysql+aiomysql://admin:admin@db:3306/petproject
      - APP_CONFIG__SMTP__HOST=mailtrap
      - APP_CONFIG__SMTP__PORT=587
      - APP_CONFIG__SMTP__USERNAME=mailtrap
      - APP_CONFIG__SMTP__PASSWORD=supersecret
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mailtrap
    networks:
      - app-network

  db:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: petproject
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  mailtrap:
    image: dbck/mailtrap:latest
    environment:
      - TZ=Europe/Berlin
      - MAILTRAP_USER=mailtrap
      - MAILTRAP_PASSWORD=supersecret
    volumes:
      - maildata:/var/mail
    ports:
      - "5151:80"
    networks:
      - app-network

volumes:
  db_data:
  maildata:


networks:
  app-network:
